### ISSUE TITLE
Tab doesn't cycle between sets after update

### ISSUE THREAD

**Issue by fcFn** [acejump/AceJump#356]
After updating to 3.7, pressing `Tab` no longer cycles between sets, instead "File is read-only" is displayed. Tested on a fresh install of GoLand 2020.3.4 with default settings and bundled plugins only.

**To Reproduce**
1. Open a file spanning more than one screen.
2. Press `Ctrl+;`.
3. Enter the search string that is found across multiple screens.
4. Press the `Tab` key.

**Expected behavior**

The next set of results is displayed.

**Desktop:**
 - OS: Windows 10
 - IDE: GoLand 2020.3.4
 - AceJump version: 3.7

**Comment by breandan** [comment]
Currently, you can only use <kbd>Enter</kbd> and <kbd>Shift</kbd>+<kbd>Enter</kbd> to cycle through the individual results. I believe this <kbd>Tab</kbd> and <kbd>Shift</kbd>+<kbd>Tab</kbd> [scrolling functionality](https://github.com/acejump/AceJump/blob/89af38422a8f75c247038c5c764e61b70d8af005/src/main/kotlin/org/acejump/control/Scroller.kt) was removed to simplify refactoring and pressing tab was intentionally [disabled](https://github.com/acejump/AceJump/issues/348#issuecomment-743705405) in #353. Previously, as you mentioned, this calculated the middle of the next/previous set of matches and centered them on the screen. If you rely on this functionality, you can roll back to [`3.6.3`](https://plugins.jetbrains.com/plugin/7086-acejump/versions/stable/89679) until it can be reimplemented. Thank you for the reminder. cc: @chylex

**Comment by fcFn** [comment]
Thank you, perhaps the README should be updated until this functionality is back.

**Comment by chylex** [comment]
Yep, sorry I forgot to remind you that this feature was missing. It's still possible to use Page Up/Down or use other IJ/GO scrolling actions if that works for you, but of course the original functionality of jumping past areas with no tags was more convenient than normal IJ/GO scrolling.

**Comment by Skorpionos** [comment]
"Enter" and "Shift+Enter" do not work too

**Comment by breandan** [comment]
This regression should be fixed in the next update, `3.8.5`. I'd like to look at #380 and release these two together.

**Comment by breandan** [comment]
This should now be available in [AceJump `3.8.5`](https://plugins.jetbrains.com/plugin/7086-acejump/versions/stable/149777). Feel free to give it a try and let us know if you have any issues.

**Comment by fcFn** [comment]
Installed 3.8.5 and still get "File is read-only" upon pressing Tab.
