### ISSUE TITLE
Stop moving to off-screen locations

### ISSUE THREAD

**Issue by tobiasETHZ** [acejump/AceJump#442]
When you do a typo while trying to jump to a location, AceJump will sometimes move to a location that is off-screen, e.g. further down in the code. There are probably some hidden matches at that location. This can bit a bit unsettling, as you sometimes randomly get moved even though you don't expect it. You have to press the back shortcut to move back to the location you were at, and restart the AceJump command from scratch. 
 
Since it's impossible that the user intentionally wants to jump to that off-screen location, I would suggest we change that behavior. Probably this can be achieved by not generating suggestions for anything off-screen.

**Comment by breandan** [comment]
You're right, this should be fixed. The only reason I can think of where you might intentionally want to select an off-screen tag is if you were scrolling through the results, saw it, scrolled past, then wanted to jump back, although accidental selection seems far more likely in practice and I can see how that would be a jarring experience.

**Comment by grafst** [comment]
So sorry to abuse this issue. But I'm trying to reach @tobiasETHZ
How are you mate? 😄

**Comment by tobiasETHZ** [comment]
@breandan thanks for the fix, this issue is back in 3.8.16 however

**Comment by breandan** [comment]
Can you provide any further details? If I understand correctly, you are saying that if the user presses a tag character that is not visible in the screen boundaries, then the plugin will jump to that tag? We disabled the off-screen tag selection feature in `3.8.15` and fixed an [edge case](https://github.com/acejump/AceJump/issues/446) in `3.8.16`, so it should be impossible to select any tag that is offscreen. You can try it by scrolling down a bit after the tags are painted, then scrolling up and selecting one of the tags that were previously visible. 

Alternatively, you could be referring to the "Keep typing" feature, which behaves like the search box in the editor. If you search for a substring in the document that is located out of the scroll boundary, AceJump will scroll to bring it in view, but should not automatically jump to that location unless its corresponding tag is selected. That feature works as intended, because searching for text highlights all matches not just on screen, but everywhere in the document. If you would like to disable this functionality, you can do so by deselecting "Search whole file" inside the AceJump settings:

![](https://user-images.githubusercontent.com/175716/259490033-1b95c4fa-b6ad-4810-abea-05c36bf00058.png)

**Comment by tobiasETHZ** [comment]
Hi,

Okay, I must have been mixing up things. I didn't know that acejump allows you to search the whole file on purpose. Looks like things are working. Thanks again for your fix
